### ISSUE TITLE
mysql模式不支持XA模式

### ISSUE THREAD

**Issue by lbj812** [oceanbase/oceanbase#1032]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
java 开发，jdbc 的mysql驱动，oceanbase驱动，都无法使用 XA模式。
```

### Fast Reproduce Steps(Required)

java 开发，jdbc 的mysql驱动，oceanbase驱动，都无法使用 XA模式。

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '0x31302e3235332e332e38373a383039313a32363132333739313936343937383136313738,0x2d3' at line 1
	at sun.reflect.GeneratedConstructorAccessor83.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

### Actual Behavior

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '0x31302e3235332e332e38373a383039313a32363132333739313936343937383136313738,0x2d3' at line 1
	at sun.reflect.GeneratedConstructorAccessor83.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: xa not support dbType: oceanbase
 at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
 at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
 at com.sun.proxy.$Proxy142.update(Unknown Source)
 at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
 at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:65)
 at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
 at com.sun.proxy.$Proxy146.updateKucunCount(Unknown Source)
 at com.vsens.mall.test.service.XATestService.updateKucun(XATestService.java:29)
 at com.vsens.mall.test.service.XATestService$$FastClassBySpringCGLIB$$1c02dfd1.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
 at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:205)
 at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:127)
 at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:202)
 at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:172)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
 at org.springframework.aop.fr

### Expected Behavior

经过钉钉咨询，回复如下:
mysql 模式不支持XA，目前只有oracle模式支持。

期望：以后的版本能后支持XA事务

**Comment by caifeizhi** [comment]
duplicate with https://github.com/oceanbase/oceanbase/issues/1033

**Comment by dimstars** [comment]
@lbj812 你好！请问你有使用中间件吗？还是直接调用数据库的XA事务接口？如果有需要的话，可以把钉钉号发到我的邮箱：[liangjinrongcm@gmail.com](mailto:liangjinrongcm@gmail.com)，我们想了解一下具体的细节。当然在issue下面交流也是可以的。
Hello, do you use middleware? Or directly call the XA transaction interface of the database? If necessary, you can send the DingTalk number to my email: [liangjinrongcm@gmail.com](mailto:liangjinrongcm@gmail.com), we would like to know the specific details. Of course, you can continue to communicate under the issue.
