### ISSUE TITLE
OBD-1006 Failed to connect to oceanbase-ce

### ISSUE THREAD

**Issue by try1995** [oceanbase/oceanbase#1087]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

error displayed in log file is
[2022-09-30 10:14:50.899] [b58bd9c6-40a8-11ed-9555-0242ac110002] [INFO] Connect to observer
[2022-09-30 10:14:50.899] [b58bd9c6-40a8-11ed-9555-0242ac110002] [DEBUG] -- connect 127.0.0.1 -P2881 -uroot -p
[2022-09-30 10:14:50.901] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] Traceback (most recent call last):
[2022-09-30 10:14:50.901] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "/usr/obd/lib/site-packages/pymysql/connections.py", line 614, in connect
[2022-09-30 10:14:50.901] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]     (self.host, self.port), self.connect_timeout, **kwargs
[2022-09-30 10:14:50.901] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "socket.py", line 724, in create_connection
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "socket.py", line 713, in create_connection
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] ConnectionRefusedError: [Errno 111] Connection refused
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] 
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] During handling of the above exception, another exception occurred:
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] 
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] Traceback (most recent call last):
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "core.py", line 1254, in start_cluster
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "_plugin.py", line 237, in __call__
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "_plugin.py", line 211, in _new_func
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "/root/.obd/plugins/oceanbase-ce/3.1.0/connect.py", line 66, in connect
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]     db, cursor = _connect(server.ip, server_config['mysql_port'], password if password is not None else '')
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "/root/.obd/plugins/oceanbase-ce/3.1.0/connect.py", line 43, in _connect
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]     db = mysql.connect(host=ip, user=user, port=int(port), password=str(password), cursorclass=mysql.cursors.DictCursor)
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "/usr/obd/lib/site-packages/pymysql/connections.py", line 353, in __init__
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]     self.connect()
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]   File "/usr/obd/lib/site-packages/pymysql/connections.py", line 664, in connect
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR]     raise exc
[2022-09-30 10:14:50.902] [b58bd9c6-40a8-11ed-9555-0242ac110002] [ERROR] pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

ip=127.0.0.1, user=root, port=2881, password=""

**Comment by hnwyllmm** [comment]
What did you do by obd?

**Comment by try1995** [comment]
> 

just run "docker run -d -p 2881:2881 -v $PWD/ob:/root/ob -v $PWD/obd:/root/.obd --name oceanbase oceanbase/oceanbase-ce"

**Comment by try1995** [comment]
I solved 
1.vi ~/.obd/cluster/obcluster/config.yaml
2.change servers:127.0.0.1 to localhost(2 replace)
3.obd cluster start obcluster or restart docker

obcluster runing
