### ISSUE TITLE
[Question]:  CPU usage is too high on Kunpeng & openEuler

### ISSUE THREAD

**Issue by FrankXMX** [oceanbase/oceanbase#1186]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

Why the IO_GETEVENT0 threads are so busy，I do nothing on observer,just started.

```
top - 16:08:56 up 8 days, 19:33,  4 users,  load average: 11.39, 11.28, 7.01
Threads: 484 total,   8 running, 476 sleeping,   0 stopped,   0 zombie
%Cpu(s): 88.9 us, 10.0 sy,  0.5 ni,  0.0 id,  0.0 wa,  0.5 hi,  0.1 si,  0.0 st
MiB Mem :  64099.8 total,   5296.6 free,   6401.4 used,  52401.7 buff/cache
MiB Swap:   2047.9 total,   2031.8 free,     16.1 used.  53675.6 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1754833 root      20   0 4764544   3.5g 119232 R  96.0   5.6  12:44.13 IO_GETEVENT0
1754837 root      20   0 4764544   3.5g 119232 R  96.0   5.6  12:46.17 IO_GETEVENT0
1754838 root      20   0 4764544   3.5g 119232 R  94.1   5.6  12:52.33 IO_GETEVENT0
1754834 root      20   0 4764544   3.5g 119232 R  91.1   5.6  12:46.16 IO_GETEVENT0
1754835 root      20   0 4764544   3.5g 119232 R  90.1   5.6  12:43.53 IO_GETEVENT0
1754832 root      20   0 4764544   3.5g 119232 R  89.1   5.6  12:43.72 IO_GETEVENT0
1754831 root      20   0 4764544   3.5g 119232 R  87.1   5.6  12:45.56 IO_GETEVENT0
1754836 root      20   0 4764544   3.5g 119232 R  85.1   5.6  12:46.60 IO_GETEVENT0
```
```
[root@host-10-208-227-136 ~]# pstack 1754837
Thread 1 (process 1754837):
#0  0x0000fffe2bd11274 in syscall () from /usr/lib64/libc.so.6
#1  0x0000fffe2be00814 in ?? () from /usr/lib64/libaio.so.1
#2  0x0000000009c8f39c in oceanbase::share::ObLocalDevice::io_getevents(oceanbase::common::ObIOContext*, long, oceanbase::common::ObIOEvents*, timespec*) ()
#3  0x00000000099ed0e4 in oceanbase::common::ObAsyncIOChannel::get_events() ()
#4  0x00000000099ecda0 in oceanbase::common::ObAsyncIOChannel::run1() ()
#5  0x000000000a8fa02c in oceanbase::lib::Threads::run(long) ()
#6  0x000000000a8f8800 in oceanbase::lib::Thread::__th_start(void*) ()
#7  0x0000fffe2bdc878c in ?? () from /usr/lib64/libpthread.so.0
#8  0x0000fffe2bd150dc in ?? () from /usr/lib64/libc.so.6
```

Why not sleep or select some time.
`polling_timeout_` = ?

CPU 100% is not allowed in our production environment.

**Comment by wayyoungboy** [comment]
This looks like a bug, about https://github.com/oceanbase/oceanbase/issues/1181  
we will fix it soon

**Comment by cyujing** [comment]
duplicate with :https://github.com/oceanbase/oceanbase/issues/1181
