### ISSUE TITLE
[BUG]ocp-express start fail

### ISSUE THREAD

**Issue by lscgzwd** [oceanbase/oceanbase#1331]
Please check the issue list for the same bug
 Please checked issue list and confirm this bug is encountered for the first time.
 Yes, I have search all issues and documents, google.
 Please try full text in English and attach precise description.
Environment
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
OceanBase V3.1.4 CE  r10000092022071511-b4bfa011ceaef428782dcb65ae89190c40b78c2f
- Hardware parameter:OS type & Compliler & CPU etc. 
CentOS 7.6 
- Others
mysql client -v5.7.23

CentOS Linux release 7.9.2009 (Core)
OB version: 4.1.0
ocp-express:
  version: 1.0.0
  package_hash: 42c6fc921063f24f9e1072d75bfa7f21f42146e3
  release: 100000432023032015.el7
mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1
Fast Reproduce Steps(Required)
Install follow this: https://www.oceanbase.com/docs/common-oceanbase-database-cn-10000000001697442
Config: mini
Start ocpexpress failed:
```
java.sql.SQLException: execute sql task failed. task: ocp_metric_expr_config, sql:INSERT INTO `ocp_metric_expr_config`(`metric`,`expr`) VALUES ('bloom_filter_cache_size','sum(ob_sysstat{stat_id=\"120009\",@LABELS}) by (@GBLABELS)') ON DUPLICATE KEY UPDATE `expr`='sum(ob_sysstat{stat_id=\"120009\",@LABELS}) by (@GBLABELS)'
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.executeSqlTask(DbInitializer.java:216)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.writeDefaultData(DbInitializer.java:254)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.install(DbInitializer.java:122)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.initialize(DbInitializer.java:101)
        at com.oceanbase.ocp.bootstrap.spring.DBInitInterceptor.afterDataSourceCreation(DBInitInterceptor.java:70)
        at com.oceanbase.ocp.bootstrap.spring.DataSourceInterceptor.lambda$afterDataSourceCreationHook$0(DataSourceInterceptor.java:43)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.oceanbase.ocp.bootstrap.spring.DataSourceInterceptor.afterDataSourceCreationHook(DataSourceInterceptor.java:41)
        at com.oceanbase.ocp.bootstrap.spring.DataSourceInterceptor.postProcessAfterInitialization(DataSourceInterceptor.java:34)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:195)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at com.oceanbase.ocp.OcpExpressApplication.main(OcpExpressApplication.java:18)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.sql.SQLTransientConnectionException: (conn=38) Timeout, query has reached the maximum query timeout: 10000000(us), maybe you can adjust the session variable ob_query_timeout or query_timeout hint, and try again.
        at com.oceanbase.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:126)
        at com.oceanbase.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:200)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatchExceptionEpilogue(OceanBaseStatement.java:370)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatch(OceanBaseStatement.java:1487)
        at com.oceanbase.ocp.bootstrap.util.SQLUtils.executeBatch(SQLUtils.java:99)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.lambda$new$0(DbInitializer.java:93)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.executeSqlTask(DbInitializer.java:203)
        ... 49 more
Caused by: com.oceanbase.jdbc.internal.util.exceptions.OceanBaseSqlException: Timeout, query has reached the maximum query timeout: 10000000(us), maybe you can adjust the session variable ob_query_timeout or query_timeout hint, and try again.
        at com.oceanbase.jdbc.internal.util.exceptions.OceanBaseSqlException.of(OceanBaseSqlException.java:80)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:190)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchAggregateSemiColon(AbstractQueryProtocol.java:1084)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchStmt(AbstractQueryProtocol.java:943)
        at com.oceanbase.jdbc.OceanBaseStatement.internalBatchExecution(OceanBaseStatement.java:1544)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatch(OceanBaseStatement.java:1484)
        ... 52 more
```
Try to set global ob_query_timeout=36000000000;

no use. 
how do I fix this problem .

**Comment by lscgzwd** [comment]
通过meta@ocp连接后，手动设置了ob_query_timeout，现在变成了，连接超时，设置了连接超时不管用

```
set GLOBAL ob_query_timeout=3216672000000000;
set GLOBAL connect_timeout=40000000;
set GLOBAL net_read_timeout=10000000;
set GLOBAL net_write_timeout=10000000;
```

```
Caused by: java.sql.SQLException: execute sql task failed. task: config_properties, sql:INSERT INTO `config_properties`(`key`,`default_value`,`need_restart`,`description`,`description_en`) VALUES ('server.servlet.session.timeout','30m',true,'登陆会话/Session超时的时间，默认是30m，最少60s。如果不加后缀单位，则默认是秒。重启生效。','Session timeout interval, default is 30m, at least 60s. If the suffix unit is not added, the default is seconds. Restart OCP to take effect.') ON DUPLICATE KEY UPDATE `description`='登陆会话/Session超时的时间，默认是30m，最少60s。如果不加后缀单位，则默认是秒。重启生效。',`description_en`='Session timeout interval, default is 30m, at least 60s. If the suffix unit is not added, the default is seconds. Restart OCP to take effect.',`need_restart`=true,`default_value`='30m'
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.executeSqlTask(DbInitializer.java:216)
        ... 49 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=164111) Connection timed out
        at com.oceanbase.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:120)
        at com.oceanbase.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:200)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatchExceptionEpilogue(OceanBaseStatement.java:370)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatch(OceanBaseStatement.java:1487)
        at com.oceanbase.ocp.bootstrap.util.SQLUtils.executeBatch(SQLUtils.java:99)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.lambda$new$0(DbInitializer.java:93)
        at com.oceanbase.ocp.bootstrap.db.DbInitializer.executeSqlTask(DbInitializer.java:203)
        ... 49 more
Caused by: com.oceanbase.jdbc.internal.util.exceptions.OceanBaseSqlException: Connection timed out
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:188)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchAggregateSemiColon(AbstractQueryProtocol.java:1084)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchStmt(AbstractQueryProtocol.java:943)
        at com.oceanbase.jdbc.OceanBaseStatement.internalBatchExecution(OceanBaseStatement.java:1544)
        at com.oceanbase.jdbc.OceanBaseStatement.executeBatch(OceanBaseStatement.java:1484)
        ... 52 more
Caused by: java.sql.SQLNonTransientConnectionException: Read timed out
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:2361)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1839)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1748)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchAggregateSemiColon(AbstractQueryProtocol.java:1080)
        ... 55 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.oceanbase.jdbc.internal.io.input.ReadAheadBufferedStream.fillBuffer(ReadAheadBufferedStream.java:148)
        at com.oceanbase.jdbc.internal.io.input.ReadAheadBufferedStream.read(ReadAheadBufferedStream.java:121)
        at com.oceanbase.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:247)
        at com.oceanbase.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:217)
        at com.oceanbase.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1837)
```

**Comment by hnwyllmm** [comment]
ocp-express is not open-source now and it is one the way.

**Comment by lscgzwd** [comment]
close, will not use oceanbase.
