### ISSUE TITLE
fedora 38 通过obd本地最小化部署失败

### ISSUE THREAD

**Issue by wencan** [oceanbase/oceanbase#1430]
OS: Fedora Linux 38 (Workstation Edition) x86_64
Kernel: 6.3.5-200.fc38.x86_64

obd cluster deploy obtest -f -c conf/mini-local-example.yaml：
```
[WARN] Use centos 7 remote mirror repository for fedora 38
+--------------------------------------------------------------------------------------------+
|                                          Packages                                          |
+--------------+---------+------------------------+------------------------------------------+
| Repository   | Version | Release                | Md5                                      |
+--------------+---------+------------------------+------------------------------------------+
| oceanbase-ce | 4.1.0.0 | 101010022023051821.el7 | 21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe |
+--------------+---------+------------------------+------------------------------------------+
Repository integrity check ok
Parameter check ok
Initializes observer work home ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository install ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository lib check !!
Try to get lib-repository
[WARN] Use centos 7 remote mirror repository for fedora 38
Package oceanbase-ce-libs-4.1.0.0-101010022023051821.el7 is available.
install oceanbase-ce-libs-4.1.0.0 for local ok
Remote oceanbase-ce-libs-4.1.0.0-101010022023051821.el7-d4b3c7985d736b73c7f01eec71b28b984184a48e repository install ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository lib check ok
obtest deployed
Trace ID: 6e7d2cde-0906-11ee-b3e8-30d042e5a832
If you want to view detailed obd logs, please run: obd display-trace 6e7d2cde-0906-11ee-b3e8-30d042e5a832
```

obd display-trace 6e7d2cde-0906-11ee-b3e8-30d042e5a832：
```
Traceback (most recent call last):
  File "obd.py", line 1676, in <module>
  File "obd.py", line 1654, in __init__
  File "obd.py", line 1420, in __init__
  File "obd.py", line 1454, in __init__
  File "obd.py", line 1482, in __init__
FileNotFoundError: [Errno 2] No such file or directory
[38013] Failed to execute script 'obd' due to unhandled exception!
```

obd cluster start obtest：
```
Traceback (most recent call last):
  File "obd.py", line 1676, in <module>
  File "obd.py", line 1654, in __init__
  File "obd.py", line 1420, in __init__
  File "obd.py", line 1454, in __init__
  File "obd.py", line 1482, in __init__
FileNotFoundError: [Errno 2] No such file or directory
[38094] Failed to execute script 'obd' due to unhandled exception!
```

**Comment by hnwyllmm** [comment]
It's a question about OBD, so I'll transfer it to OBD repo.
