### ISSUE TITLE
[Feature]: Modify char type to other data types not supported 

### ISSUE THREAD

**Issue by billguocs** [oceanbase/oceanbase#1568]
**Use Case**

OB version: 5.7.25-OceanBase-v3.2.4.5 (Enterprise)
```sql
ALTER TABLE table ADD field_test CHAR(1) DEFAULT '' NULL
ALTER TABLE table MODIFY field_test VARCHAR(256) DEFAULT '' NULL
```
执行表结构变更的时候，发生报错，见Additional context

**Describe the solution you'd like**

其他数据库支持此操作，ob也应该支持char to other type

**Describe alternatives you've considered**

不确定是否是版本问题

**Additional context**

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1235] [0A000]: Modify char type to other data types not supported
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3940)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5142)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Modify char type to other data types not supported
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

**Comment by hnwyllmm** [comment]
This feature is supported by 4.x:
```
obclient> create table t(id int);
Query OK, 0 rows affected (0.89 sec)

obclient> ALTER TABLE t ADD field_test CHAR(1) DEFAULT '' NULL;
Query OK, 0 rows affected (0.69 sec)

obclient> ALTER TABLE t MODIFY field_test VARCHAR(256) DEFAULT '' NULL;
Query OK, 0 rows affected (1.56 sec)

obclient>
```
