### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by liujun69** [oceanbase/oceanbase#1605]
**Describe the bug**
      Here is a springboot project that uses Flyway Java API as the database version tool. Every time it starts, it automatically executes the maintenance SQL script. The problem occurs when the table creation statement includes foreign key creation. If there are default values for any fields, it will prompt java. sql. SQLException: Cannot add foreign key constraint, foreign key creation failed;When I remove the default values, both the table and foreign keys can execute normally. The driver used in the project is MySQL driver

**Environment**
Server: openEuler 22.03
flyway:  https://github.com/flyway/flyway/pull/3571(package by myself)
`
<dependency>
	<groupId>org.flywaydb</groupId>
	<artifactId>flyway-core</artifactId>
	<version>8.5.11</version>
	  </dependency>
<dependency>
	<groupId>org.flywaydb</groupId>
	<artifactId>flyway-mysql</artifactId>
	<version>8.5.11</version>
</dependency>
mysql jdbc:
<dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>5.1.36</version>
</dependency>
`
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  OceanBase Version: 5.7.25-OceanBase_CE-v4.2.0.0

**Fast Reproduce Steps(Required)**
Add a script file to the specified version directory in Flyway, including the following table creation statement
`
CREATE TABLE supplier_groups(
   group_id bigint(20) not null,
   group_name VARCHAR(127) NOT null,
   primary key (group_id)
);

CREATE TABLE suppliers(
   supplier_id bigint(20) not null,
   supplier_name VARCHAR(127) default 'default' NOT NULL,
   group_id bigint(20) NOT NULL,
   PRIMARY KEY(supplier_id),
   CONSTRAINT fk_name FOREIGN KEY(group_id) references supplier_groups(group_id)
 );
`
And Then start the project.
In addition, I can also reproduce the above statements in the latest version of DBeaver

**Expected behavior**
Normal table creation and foreign keys

**Actual Behavior**
Table created successfully but foreign key not created successfully

**Comment by hnwyllmm** [comment]
I tried to reproduce the case by SQL but failed.
The exception was raised by flyway itself?

**Comment by liujun69** [comment]
> I tried to reproduce the case by SQL but failed. The exception was raised by flyway itself?
The exception raised by flyway as follow
at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:69)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:58)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$$Lambda$27/448084064.call(Unknown Source)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:377)
But it is reproduced in DBeaver. So is this a compatibility issue in both Flyway and DBeaver？
And then I try it in obclient as follow
```
obclient [mysql]> CREATE TABLE supplier_groups(
    ->    group_id bigint(20) not null,
    ->    group_name VARCHAR(127) NOT null,
    ->    primary key (group_id)
    -> );
Query OK, 0 rows affected (0.458 sec)

obclient [mysql]> CREATE TABLE suppliers(
    ->    supplier_id bigint(20) not null,
    ->    supplier_name VARCHAR(127) default 'default' NOT NULL,
    ->    group_id bigint(20) NOT NULL,
    ->    PRIMARY KEY(supplier_id),
    ->    CONSTRAINT fk_name FOREIGN KEY(group_id) references supplier_groups(group_id)
    ->  );
Query OK, 0 rows affected (0.571 sec)

obclient [mysql]> desc suppliers;
+---------------+--------------+------+-----+---------+-------+
| Field         | Type         | Null | Key | Default | Extra |
+---------------+--------------+------+-----+---------+-------+
| supplier_id   | bigint(20)   | NO   | PRI | NULL    |       |
| supplier_name | varchar(127) | NO   |     | default |       |
| group_id      | bigint(20)   | NO   |     | NULL    |       |
+---------------+--------------+------+-----+---------+-------+
3 rows in set (0.025 sec)
obclient [ghc_bm_fp]> select * from information_schema.REFERENTIAL_CONSTRAINTS where TABLE_NAME ='suppliers';
Empty set (0.015 sec)
```
The result in Obclient is that the table was successfully created but the foreign key was not created

**Comment by hnwyllmm** [comment]
It's interesting. Below is my result:
```
| suppliers | CREATE TABLE `suppliers` (
  `supplier_id` bigint(20) NOT NULL,
  `supplier_name` varchar(127) NOT NULL DEFAULT 'default',
  `group_id` bigint(20) NOT NULL,
  PRIMARY KEY (`supplier_id`),
  CONSTRAINT `fk_name` FOREIGN KEY (`group_id`) REFERENCES `test`.`supplier_groups`(`group_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0 |

obclient> select * from information_schema.REFERENTIAL_CONSTRAINTS where TABLE_NAME ='suppliers';
+--------------------+-------------------+-----------------+---------------------------+--------------------------+------------------------+--------------+-------------+-------------+------------+-----------------------+
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME | UNIQUE_CONSTRAINT_CATALOG | UNIQUE_CONSTRAINT_SCHEMA | UNIQUE_CONSTRAINT_NAME | MATCH_OPTION | UPDATE_RULE | DELETE_RULE | TABLE_NAME | REFERENCED_TABLE_NAME |
+--------------------+-------------------+-----------------+---------------------------+--------------------------+------------------------+--------------+-------------+-------------+------------+-----------------------+
| def                | test              | fk_name         | def                       | test                     | PRIMARY                | NONE         | RESTRICT    | RESTRICT    | suppliers  | supplier_groups       |
+--------------------+-------------------+-----------------+---------------------------+--------------------------+------------------------+--------------+-------------+-------------+------------+-----------------------+
1 row in set (0.20 sec)
```

**Comment by hnwyllmm** [comment]
The foreign key is created successfully.

**Comment by liujun69** [comment]
I tried using the script you provided, but the result still hasn't changed (~。~).Does this related with the dependent environment?

```
obclient [mysql]> CREATE TABLE `suppliers` (
    ->   `supplier_id` bigint(20) NOT NULL,
    ->   `supplier_name` varchar(127) NOT NULL DEFAULT 'default',
    ->   `group_id` bigint(20) NOT NULL,
    ->   PRIMARY KEY (`supplier_id`),
    ->   CONSTRAINT `fk_name` FOREIGN KEY (`group_id`) REFERENCES `mysql`.`supplier_groups`(`group_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
    -> ) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
Query OK, 0 rows affected (0.751 sec)

obclient [mysql]> select * from information_schema.REFERENTIAL_CONSTRAINTS where TABLE_NAME ='suppliers';
Empty set (0.003 sec)
```

**Comment by hnwyllmm** [comment]
Can you upgrade to the latest version and try again?

**Comment by liujun69** [comment]
V4.2.1_CE?

**Comment by hnwyllmm** [comment]
I tried again based on V4.2.1 and it works.
You can try it with `obd demo -c oceanbase-ce` and `obd` always fetch the latest version.
