### ISSUE TITLE
[Bug]: cannot close result set

### ISSUE THREAD

**Issue by AlexKaiqi** [oceanbase/oceanbase#1778]
**Describe the bug**

ResultSet resultset = connection.getMetaData().getTables(...);
resultSet.close();
Close the resultset by the given step, an stackoverflow error will be thrown.
Not all resultset cann't be close, this is the only one I found by now.
java.lang.StackOverflowError
	at com.oceanbase.jdbc.OceanBaseStatement.realClose(OceanBaseStatement.java:948)
	at com.oceanbase.jdbc.OceanBaseStatement.close(OceanBaseStatement.java:944)
	at com.oceanbase.jdbc.OceanBaseStatement.checkCloseOnCompletion(OceanBaseStatement.java:1744)
	at com.oceanbase.jdbc.JDBC4ResultSet.realClose(JDBC4ResultSet.java:795)
	at com.oceanbase.jdbc.JDBC4ResultSet.close(JDBC4ResultSet.java:760)
	at com.oceanbase.jdbc.OceanBaseStatement.realClose(OceanBaseStatement.java:958)
	at com.oceanbase.jdbc.OceanBaseStatement.close(OceanBaseStatement.java:944)
	at com.oceanbase.jdbc.OceanBaseStatement.checkCloseOnCompletion(OceanBaseStatement.java:1744)
**Environment**

- OS Version and CPU Arch(`uname -a`):
  23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64
  or x86_64 Linux 
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  com.oceanbase.jdbc.Driver:oceanbase-client:2.4.1

**Fast Reproduce Steps(Required)**
ResultSet resultset = connection.getMetaData().getTables(...);
resultSet.close();
just close the result set.
**Expected behavior**

**Actual Behavior**

The resultset is properly closed
**Additional context**

**Comment by hnwyllmm** [comment]
Please contact your expert support and you'll get response better and we don't have information about jdbc enterprise edition.
