### ISSUE TITLE
[Bug]: Docker deploy Error: paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.17.0.5

### ISSUE THREAD

**Issue by brealisty** [oceanbase/oceanbase#2198]
**Describe the bug**
使用docker的方式部署成功，后面不知道为什么容器处于停止状态，再次启动就启动不了了，查看日志报错：
 paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.17.0.5

**Environment**
- OS Version and CPU Arch(`uname -a`):
  Ubuntu 22.04 amd64

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  [root@af9cd042fc5b ~]# obd --version
  OceanBase Deploy: 2.10.0

**Log info**
[root@af9cd042fc5b ~]#  obd display-trace f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:05.165] [DEBUG] - cmd: ['obcluster']
[2024-12-12 06:26:05.165] [DEBUG] - opts: {'servers': None, 'components': None, 'force_delete': None, 'strict_check': None, 'without_parameter': None}
[2024-12-12 06:26:05.166] [DEBUG] - mkdir /root/.obd/lock/
[2024-12-12 06:26:05.166] [DEBUG] - unknown lock mode
[2024-12-12 06:26:05.166] [DEBUG] - try to get share lock /root/.obd/lock/global
[2024-12-12 06:26:05.166] [DEBUG] - share lock `/root/.obd/lock/global`, count 1
[2024-12-12 06:26:05.166] [DEBUG] - Get Deploy by name
[2024-12-12 06:26:05.166] [DEBUG] - mkdir /root/.obd/cluster/
[2024-12-12 06:26:05.167] [DEBUG] - mkdir /root/.obd/config_parser/
[2024-12-12 06:26:05.167] [DEBUG] - try to get exclusive lock /root/.obd/lock/deploy_obcluster
[2024-12-12 06:26:05.167] [DEBUG] - exclusive lock `/root/.obd/lock/deploy_obcluster`, count 1
[2024-12-12 06:26:05.172] [DEBUG] - Deploy status judge
[2024-12-12 06:26:05.172] [INFO] Get local repositories
[2024-12-12 06:26:05.173] [DEBUG] - mkdir /root/.obd/repository
[2024-12-12 06:26:05.173] [DEBUG] - Get local repository oceanbase-ce-4.2.1.9-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.173] [DEBUG] - Search repository oceanbase-ce version: 4.2.1.9, tag: 42a3a6adf515add3d4c804aad736ebd6fc944c7d, release: None, package_hash: None
[2024-12-12 06:26:05.173] [DEBUG] - try to get share lock /root/.obd/lock/mirror_and_repo
[2024-12-12 06:26:05.173] [DEBUG] - share lock `/root/.obd/lock/mirror_and_repo`, count 1
[2024-12-12 06:26:05.173] [DEBUG] - mkdir /root/.obd/repository/oceanbase-ce
[2024-12-12 06:26:05.176] [DEBUG] - Found repository oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.176] [DEBUG] - Get deploy config
[2024-12-12 06:26:05.185] [INFO] Search plugins
[2024-12-12 06:26:05.185] [DEBUG] - Searching start_check plugin for components ...
[2024-12-12 06:26:05.185] [DEBUG] - Searching start_check plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.185] [DEBUG] - mkdir /root/.obd/plugins
[2024-12-12 06:26:05.186] [DEBUG] - Found for oceanbase-ce-py_script_start_check-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.186] [DEBUG] - Searching create_tenant plugin for components ...
[2024-12-12 06:26:05.186] [DEBUG] - Searching create_tenant plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.187] [DEBUG] - Found for oceanbase-ce-py_script_create_tenant-4.2.0.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.187] [DEBUG] - Searching tenant_optimize plugin for components ...
[2024-12-12 06:26:05.187] [DEBUG] - Searching tenant_optimize plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.188] [DEBUG] - No such tenant_optimize plugin for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.188] [DEBUG] - Searching start plugin for components ...
[2024-12-12 06:26:05.188] [DEBUG] - Searching start plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.188] [DEBUG] - Found for oceanbase-ce-py_script_start-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.189] [DEBUG] - Searching connect plugin for components ...
[2024-12-12 06:26:05.189] [DEBUG] - Searching connect plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.189] [DEBUG] - Found for oceanbase-ce-py_script_connect-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.189] [DEBUG] - Searching bootstrap plugin for components ...
[2024-12-12 06:26:05.189] [DEBUG] - Searching bootstrap plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.190] [DEBUG] - Found for oceanbase-ce-py_script_bootstrap-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.190] [DEBUG] - Searching display plugin for components ...
[2024-12-12 06:26:05.190] [DEBUG] - Searching display plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.190] [DEBUG] - Found for oceanbase-ce-py_script_display-3.1.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.191] [INFO] Load cluster param plugin
[2024-12-12 06:26:05.191] [DEBUG] - Get local repository oceanbase-ce-4.2.1.9-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.191] [DEBUG] - Searching param plugin for components ...
[2024-12-12 06:26:05.191] [DEBUG] - Search param plugin for oceanbase-ce
[2024-12-12 06:26:05.191] [DEBUG] - Found for oceanbase-ce-param-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.192] [DEBUG] - Applying oceanbase-ce-param-4.2.1.4 for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.749] [INFO] Cluster status check
[2024-12-12 06:26:05.749] [DEBUG] - Searching status plugin for components ...
[2024-12-12 06:26:05.749] [DEBUG] - Searching status plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.749] [DEBUG] - Found for oceanbase-ce-py_script_status-3.1.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.753] [DEBUG] - host: 172.17.0.5, port: 22, user: root, password: None
[2024-12-12 06:26:08.827] [ERROR] Traceback (most recent call last):
[2024-12-12 06:26:08.827] [ERROR]   File "core.py", line 2104, in start_cluster
[2024-12-12 06:26:08.827] [ERROR]   File "core.py", line 2148, in _start_cluster
[2024-12-12 06:26:08.827] [ERROR]   File "core.py", line 1011, in cluster_status_check
[2024-12-12 06:26:08.827] [ERROR]   File "core.py", line 194, in call_plugin
[2024-12-12 06:26:08.827] [ERROR]   File "core.py", line 260, in get_clients
[2024-12-12 06:26:08.828] [ERROR]   File "core.py", line 279, in get_clients_with_connect_status
[2024-12-12 06:26:08.828] [ERROR]   File "core.py", line 315, in ssh_clients_connect
[2024-12-12 06:26:08.828] [ERROR]   File "_stdio.py", line 956, in func_wrapper
[2024-12-12 06:26:08.828] [ERROR]   File "ssh.py", line 443, in connect
[2024-12-12 06:26:08.828] [ERROR]   File "_stdio.py", line 956, in func_wrapper
[2024-12-12 06:26:08.828] [ERROR]   File "ssh.py", line 400, in _login
[2024-12-12 06:26:08.828] [ERROR]   File "paramiko/client.py", line 368, in connect
[2024-12-12 06:26:08.828] [ERROR] paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.17.0.5
[2024-12-12 06:26:08.828] [ERROR]
[2024-12-12 06:26:08.828] [CRITICAL] [ERROR] OBD-1013: root@172.17.0.5 connect failed: time out
[2024-12-12 06:26:08.829] [INFO] [ERROR] OBD-1013: root@172.17.0.5 connect failed: time out
[2024-12-12 06:26:08.829] [INFO]
[2024-12-12 06:26:08.829] [INFO] Trace ID: f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:08.829] [INFO] If you want to view detailed obd logs, please run: obd display-trace f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/global
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/deploy_obcluster
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/mirror_and_repo

---
**Describe the bug**
The deployment using docker was successful, but I don’t know why the container was stopped later and could not be started again. Check the log and get an error:
 paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.17.0.5

**Environment**
- OS Version and CPU Arch(`uname -a`):
  Ubuntu 22.04 amd64

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  [root@af9cd042fc5b ~]# obd --version
  OceanBase Deploy: 2.10.0

**Log info**
[root@af9cd042fc5b ~]# obd display-trace f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:05.165] [DEBUG] - cmd: ['obcluster']
[2024-12-12 06:26:05.165] [DEBUG] - opts: {'servers': None, 'components': None, 'force_delete': None, 'strict_check': None, 'without_parameter': None}
[2024-12-12 06:26:05.166] [DEBUG] - mkdir /root/.obd/lock/
[2024-12-12 06:26:05.166] [DEBUG] - unknown lock mode
[2024-12-12 06:26:05.166] [DEBUG] - try to get share lock /root/.obd/lock/global
[2024-12-12 06:26:05.166] [DEBUG] - share lock `/root/.obd/lock/global`, count 1
[2024-12-12 06:26:05.166] [DEBUG] - Get Deploy by name
[2024-12-12 06:26:05.166] [DEBUG] - mkdir /root/.obd/cluster/
[2024-12-12 06:26:05.167] [DEBUG] - mkdir /root/.obd/config_parser/
[2024-12-12 06:26:05.167] [DEBUG] - try to get exclusive lock /root/.obd/lock/deploy_obcluster
[2024-12-12 06:26:05.167] [DEBUG] - exclusive lock `/root/.obd/lock/deploy_obcluster`, count 1
[2024-12-12 06:26:05.172] [DEBUG] - Deploy status judge
[2024-12-12 06:26:05.172] [INFO] Get local repositories
[2024-12-12 06:26:05.173] [DEBUG] - mkdir /root/.obd/repository
[2024-12-12 06:26:05.173] [DEBUG] - Get local repository oceanbase-ce-4.2.1.9-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.173] [DEBUG] - Search repository oceanbase-ce version: 4.2.1.9, tag: 42a3a6adf515add3d4c804aad736ebd6fc944c7d, release: None, package_hash: None
[2024-12-12 06:26:05.173] [DEBUG] - try to get share lock /root/.obd/lock/mirror_and_repo
[2024-12-12 06:26:05.173] [DEBUG] - share lock `/root/.obd/lock/mirror_and_repo`, count 1
[2024-12-12 06:26:05.173] [DEBUG] - mkdir /root/.obd/repository/oceanbase-ce
[2024-12-12 06:26:05.176] [DEBUG] - Found repository oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.176] [DEBUG] - Get deploy config
[2024-12-12 06:26:05.185] [INFO] Search plugins
[2024-12-12 06:26:05.185] [DEBUG] - Searching start_check plugin for components ...
[2024-12-12 06:26:05.185] [DEBUG] - Searching start_check plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.185] [DEBUG] - mkdir /root/.obd/plugins
[2024-12-12 06:26:05.186] [DEBUG] - Found for oceanbase-ce-py_script_start_check-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.186] [DEBUG] - Searching create_tenant plugin for components ...
[2024-12-12 06:26:05.186] [DEBUG] - Searching create_tenant plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.187] [DEBUG] - Found for oceanbase-ce-py_script_create_tenant-4.2.0.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.187] [DEBUG] - Searching tenant_optimize plugin for components ...
[2024-12-12 06:26:05.187] [DEBUG] - Searching tenant_optimize plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.188] [DEBUG] - No such tenant_optimize plugin for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.188] [DEBUG] - Searching start plugin for components ...
[2024-12-12 06:26:05.188] [DEBUG] - Searching start plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.188] [DEBUG] - Found for oceanbase-ce-py_script_start-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.189] [DEBUG] - Searching connect plugin for components ...
[2024-12-12 06:26:05.189] [DEBUG] - Searching connect plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.189] [DEBUG] - Found for oceanbase-ce-py_script_connect-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.189] [DEBUG] - Searching bootstrap plugin for components ...
[2024-12-12 06:26:05.189] [DEBUG] - Searching bootstrap plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.190] [DEBUG] - Found for oceanbase-ce-py_script_bootstrap-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.190] [DEBUG] - Searching display plugin for components ...
[2024-12-12 06:26:05.190] [DEBUG] - Searching display plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.190] [DEBUG] - Found for oceanbase-ce-py_script_display-3.1.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.191] [INFO] Load cluster param plugin
[2024-12-12 06:26:05.191] [DEBUG] - Get local repository oceanbase-ce-4.2.1.9-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.191] [DEBUG] - Searching param plugin for components ...
[2024-12-12 06:26:05.191] [DEBUG] - Search param plugin for oceanbase-ce
[2024-12-12 06:26:05.191] [DEBUG] - Found for oceanbase-ce-param-4.2.1.4 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.192] [DEBUG] - Applying oceanbase-ce-param-4.2.1.4 for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.749] [INFO] Cluster status check
[2024-12-12 06:26:05.749] [DEBUG] - Searching status plugin for components ...
[2024-12-12 06:26:05.749] [DEBUG] - Searching status plugin for oceanbase-ce-4.2.1.9-109000032024092015.el8-42a3a6adf515add3d4c804aad736ebd6fc944c7d
[2024-12-12 06:26:05.749] [DEBUG] - Found for oceanbase-ce-py_script_status-3.1.0 for oceanbase-ce-4.2.1.9
[2024-12-12 06:26:05.753] [DEBUG] - host: 172.17.0.5, port: 22, user: root, password: None
[2024-12-12 06:26:08.827] [ERROR] Traceback (most recent call last):
[2024-12-12 06:26:08.827] [ERROR] File "core.py", line 2104, in start_cluster
[2024-12-12 06:26:08.827] [ERROR] File "core.py", line 2148, in _start_cluster
[2024-12-12 06:26:08.827] [ERROR] File "core.py", line 1011, in cluster_status_check
[2024-12-12 06:26:08.827] [ERROR] File "core.py", line 194, in call_plugin
[2024-12-12 06:26:08.827] [ERROR] File "core.py", line 260, in get_clients
[2024-12-12 06:26:08.828] [ERROR] File "core.py", line 279, in get_clients_with_connect_status
[2024-12-12 06:26:08.828] [ERROR] File "core.py", line 315, in ssh_clients_connect
[2024-12-12 06:26:08.828] [ERROR] File "_stdio.py", line 956, in func_wrapper
[2024-12-12 06:26:08.828] [ERROR] File "ssh.py", line 443, in connect
[2024-12-12 06:26:08.828] [ERROR] File "_stdio.py", line 956, in func_wrapper
[2024-12-12 06:26:08.828] [ERROR] File "ssh.py", line 400, in _login
[2024-12-12 06:26:08.828] [ERROR] File "paramiko/client.py", line 368, in connect
[2024-12-12 06:26:08.828] [ERROR] paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.17.0.5
[2024-12-12 06:26:08.828] [ERROR]
[2024-12-12 06:26:08.828] [CRITICAL] [ERROR] OBD-1013: root@172.17.0.5 connect failed: time out
[2024-12-12 06:26:08.829] [INFO] [ERROR] OBD-1013: root@172.17.0.5 connect failed: time out
[2024-12-12 06:26:08.829] [INFO]
[2024-12-12 06:26:08.829] [INFO] Trace ID: f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:08.829] [INFO] If you want to view detailed obd logs, please run: obd display-trace f73db6b4-b851-11ef-94a2-0242ac110002
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/global
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/deploy_obcluster
[2024-12-12 06:26:08.830] [DEBUG] - unlock /root/.obd/lock/mirror_and_repo

**Comment by brealisty** [comment]
神奇，重启电脑之后又好了。

**Comment by wpleonardo** [comment]
> 神奇，重启电脑之后又好了。
> 
> Miraculously, it was fine again after restarting the computer.

Great! Keep in touch, bro.

**Comment by brealisty** [comment]
.....又出现这个问题了，docker部署很不稳定啊

**Comment by wpleonardo** [comment]
I have reopened this issue, and our DEV team will help you check this issue promptly.

**Comment by chris-sun-star** [comment]
Can you check the ip address in your docker container, if you start it with normal or mini mode, it will use the container's ip address to bootstrap the observer, if the ip address changed after restart, then the observer will fail to start.
To avoid this problem, you may specify the observer to bootstrap with '127.0.0.1', this can be done by passing an environment variable OB_SERVER_IP='127.0.0.1'
