### ISSUE TITLE
What is the error "java.sql.SQLException: The observer or zone is not the master"?

### ISSUE THREAD

**Issue by mrhanice** [oceanbase/oceanbase#390]
When I read data from OceanBase table use Spark mysql JDBC  in parallel, it occurs this error "java.sql.SQLException: The observer or zone is not the master" .
More details are:
21/10/13 07:57:22 ERROR Executor: Exception in task 58.0 in stage 0.0 (TID 58)
java.sql.SQLException: The observer or zone is not the master
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2115)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1989)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3410)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:470)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3112)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2341)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2736)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.compute(JDBCRDD.scala:413)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:359)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:357)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:308)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by longdafeng** [comment]
@whhe  please take a look at this issue.

**Comment by whhe** [comment]
Sorry for late reply, could you please provide more details of your environment? I will firstly try to reproduce it ASAP.

**Comment by 690697134** [comment]
> Sorry for late reply, could you please provide more details of your environment? I will firstly try to reproduce it ASAP.

Suppose there is a 96-partitioned table lineitem(This table is one of tables in TPC-H ).
When I run  
SELECT /*+    parallel(3) */   `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 );
SELECT /*+    parallel(3) */   `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50 p51 p52 p53 p54 p55 p56 p57 p58 p59 p60 p61 p62 p63 );
SELECT /*+    parallel(3) */   `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p64 p65 p66 p67 p68 p69 p70 p71 p72 p73 p74 p75 p76 p77 p78 p79 p80 p81 p82 p83 p84 p85 p86 p87 p88 p89 p90 p91 p92 p93 p94 p95 );
concurrently, this error occurs.

**Comment by whhe** [comment]
> > Sorry for late reply, could you please provide more details of your environment? I will firstly try to reproduce it ASAP.
> 
> Suppose there is a 96-partitioned table lineitem(This table is one of tables in TPC-H ). When I run SELECT /*+ parallel(3) _/ `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 ); SELECT /_+ parallel(3) _/ `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50 p51 p52 p53 p54 p55 p56 p57 p58 p59 p60 p61 p62 p63 ); SELECT /_+ parallel(3) */ `l_suppkey`,`l_quantity` FROM lineitem PARTITION (p64 p65 p66 p67 p68 p69 p70 p71 p72 p73 p74 p75 p76 p77 p78 p79 p80 p81 p82 p83 p84 p85 p86 p87 p88 p89 p90 p91 p92 p93 p94 p95 ); concurrently, sometimes this error occurs.

OK, I will try to reproduce this problem next week.

**Comment by 690697134** [comment]
thanks!



---Original---
From: "He ***@***.***&gt;
Date: Sun, Dec 19, 2021 16:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [oceanbase/oceanbase] What is the error "java.sql.SQLException:The observer or zone is not the master"? (#390)




   
Sorry for late reply, could you please provide more details of your environment? I will firstly try to reproduce it ASAP.
  
Suppose there is a 96-partitioned table lineitem(This table is one of tables in TPC-H ). When I run SELECT /*+ parallel(3) / l_suppkey,l_quantity FROM lineitem PARTITION (p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 ); SELECT /+ parallel(3) / l_suppkey,l_quantity FROM lineitem PARTITION (p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50 p51 p52 p53 p54 p55 p56 p57 p58 p59 p60 p61 p62 p63 ); SELECT /+ parallel(3) */ l_suppkey,l_quantity FROM lineitem PARTITION (p64 p65 p66 p67 p68 p69 p70 p71 p72 p73 p74 p75 p76 p77 p78 p79 p80 p81 p82 p83 p84 p85 p86 p87 p88 p89 p90 p91 p92 p93 p94 p95 ); concurrently, sometimes this error occurs.
  
OK, I will try to reproduce this problem next week.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whhe** [comment]
Hi @690697134 

Sorry for the late reply. I tested the select clause on Spark many times, but there is no such exception encountered.

My environment: 
- Spark 3.2.0 with Hadoop builtin.
- OceanBase: 3.1.2-OceanBase CE, 3 servers with obproxy.
- Driver: mysql-connector-java-5.1.47.jar

I tried both connecting directly or through obproxy, and I think this is not a issue about Spark or MySQL driver.

By the way, did you connect to OBServer by obproxy? If it still not work by using obproxy, maybe you can create a ticket at https://open.oceanbase.com/answer with your obproxy/observer log attached.
