### ISSUE TITLE
[voice of client]DOOBA's log isn't clear

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#545]
客户上线后, 回访问题跟踪

DOOBA 工具，报错信息不清晰, 无法排查

**Comment by longdafeng** [comment]
![image](https://user-images.githubusercontent.com/374091/142711542-300c56de-1f09-4080-8876-cd61a0d440e8.png)
从报错其实看不出来任何信息，最后发现是没装 mysql导致的。dooba 脚本里面有一步是要装 mysql client 再去连 OB

**Comment by hnwyllmm** [comment]
```
Traceback (most recent call last):
  File "dooba.py", line 3828, in <module>
    DoobaMain()
  File "dooba.py", line 3796, in __init__
    curses.wrapper(Dooba)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "dooba.py", line 3630, in __init__
    oceanbase.update_tenant_info()
  File "dooba.py", line 1614, in update_tenant_info
    res = self.dosql("select tenant_id, tenant_name, zone_list from __all_tenant")
  File "dooba.py", line 1086, in dosql
    raise Exception('please install mysql', cmd)
Exception: ('please install mysql', 'mysql -V')
```
现在的提示比较友好
