### ISSUE TITLE
TPC-C测试运行runBenchmark时失败

### ISSUE THREAD

**Issue by coding01000** [oceanbase/oceanbase#55]
>17:06:13,277 [Thread-10] ERROR  jTPCCTData : Unexpected SQLException in PAYMENT
17:06:13,277 [Thread-10] ERROR  jTPCCTData : Not supported feature or function
java.sql.SQLException: Not supported feature or function
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
	at jTPCCTData.executePayment(jTPCCTData.java:929)
	at jTPCCTData.execute(jTPCCTData.java:99)
	at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:160)
	at jTPCCTerminal.run(jTPCCTerminal.java:88)
	at java.lang.Thread.run(Thread.java:748)

the version of mysql connector is 5.1.47 ，
the test process follows https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/test-the-tpc-c-of-apsaradb-for-oceanbase

**Comment by lemon0910** [comment]
First try to find which SQL is wrong in client log. After that, search the sql in observer.log to find more information.

**Comment by coding01000** [comment]
the foreign key constraint causes the SQL execution to fail
delete run/sql.common/foreignKeys.sql
