### ISSUE TITLE
OCP failed to install new cluster in the step of 20/48

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#753]
```
2022-01-11 20:33:15.664  WARN 44 --- [pool-subtask-executor-thread-37,be5bcde22b6d42c7,66afb64c3e99] c.a.ocp.core.job.runner.RunnerFactory    : Execute task failed, subtask=SubtaskInstanceEntity{id=9559, name=Bootstrap ob, state=FAILED, operation=RETRY, className=com.alipay.ocp.service.task.business.cluster.BootStrapObTask, seriesId=40, startTime=2022-01-11T20:32:02.113+08:00, endTime=2022-01-11T20:33:15.664+08:00}, failedMessage=RPC execution failed.server: 172.30.62.228 port: 62888 command: admin mysql -h127.1 -P2881 -uroot -e "set ob_query_timeout=600000000; ALTER SYSTEM BOOTSTRAP  REGION 'zone1' ZONE 'zone1' SERVER '172.30.62.228:2882', REGION 'zone1' ZONE 'zone2' SERVER '172.30.62.229:2882', REGION 'zone1' ZONE 'zone3' SERVER '172.30.62.230:2882' ;" code: 1 result: ERROR 1235 (0A000) at line 1: unit min memory less than __min_full_resource_pool_memory not supported

com.alipay.ocp.core.exception.UnexpectedException: [OCP UnexpectedException]: status=500 INTERNAL_SERVER_ERROR, errorCode=COMMON_RPC_EXECUTE_FAILED, args=172.30.62.228,62888,admin mysql -h127.1 -P2881 -uroot -e "set ob_query_timeout=600000000; ALTER SYSTEM BOOTSTRAP  REGION 'zone1' ZONE 'zone1' SERVER '172.30.62.228:2882', REGION 'zone1' ZONE 'zone2' SERVER '172.30.62.229:2882', REGION 'zone1' ZONE 'zone3' SERVER '172.30.62.230:2882' ;",1,ERROR 1235 (0A000) at line 1: unit min memory less than __min_full_resource_pool_memory not supported
	at com.alipay.ocp.core.task.util.OcpAgentUtils.executePosMethod(OcpAgentUtils.java:272) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.task.util.OcpAgentUtils.callPosMethod(OcpAgentUtils.java:135) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.task.util.OcpAgentUtils.runCmd(OcpAgentUtils.java:57) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.service.compute.host.HostManager.executeRpcCommand(HostManager.java:91) ~[ocp-service-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.service.task.business.cluster.BootStrapObTask.run(BootStrapOb
Task.java:130) ~[ocp-service-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.task.task.ITask.retry(ITask.java:45) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.metadb.job.model.SubtaskInstanceEntity.retry(SubtaskInstanceEntity.java:225) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.runner.JavaTaskRunner.doExecute(JavaTaskRunner.java:30) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.runner.JavaTaskRunner.run(JavaTaskRunner.java:20) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.runner.RunnerFactory.doRun(RunnerFactory.java:103) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.runner.RunnerFactory.redirectOutputIfNotSysSchedule(RunnerFactory.java:147) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.runner.RunnerFactory.run(RunnerFactory.java:92) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at com.alipay.ocp.core.job.coordinator.worker.subtask.ReadySubtaskWorker.lambda$submitTask$2(ReadySubtaskWorker.java:123) ~[ocp-core-3.1.1-20210916.jar!/:3.1.1-20210916]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]

```

ecs hardware is 16c/64g

**Comment by longdafeng** [comment]
Suggest OCP add one logic to detect the ecs's resource like OBD autodeploy. 

It will generate one configuration, if user add more setting, the user's setting will replace the default configuration

**Comment by longdafeng** [comment]
This bug has been fixed in the latest version 4.x
