### ISSUE TITLE
[Bug]: java.sql.SQLException: Not supported feature or function

### ISSUE THREAD

**Issue by superzZZ** [oceanbase/oceanbase#884]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB 社区版  ce 3.1.2
-  CentOS Linux release 7.5.1804 (Core)
```

### Fast Reproduce Steps(Required)

1开启_ob_enable_prepared_statement隐含参数
2 应用查询查询select FDATA from T_META_FORM where FNUMBER = ? and FKEY = ? and FTYPE = ?
Key: getConfig
TraceId：6cf20126f17a05e
Instance：bak-sys-8262205764
发生时间：Wed Apr 20 09:34:19 GMT+08:00 2022
===================================================
调用堆栈：
java.sql.SQLException: Not supported feature or function
RequestContext: tenantId=perf-baseline-bak, accountId=1401415136895306752
TX: TXContext.299022:tag=Implicit-transaction, level=1, propagation=NOT_SUPPORTED, rollback=false, halt=false, ended=false
SQL: select FDATA from T_META_FORM where FNUMBER = ? and FKEY = ? and FTYPE = ?
	at kd.bos.db.ExceptionWrapper.wrapSQLException(ExceptionWrapper.java:202)
	at kd.bos.db.ExceptionWrapper.wrapperRethrowCause(ExceptionWrapper.java:128)
	at kd.bos.db.ExceptionWrapper.wrapper(ExceptionWrapper.java:55)
	at kd.bos.db.ExceptionWrapper.getLogCause(ExceptionWrapper.java:96)
	at kd.bos.db.BaseDB.rethrow(BaseDB.java:563)
	at kd.bos.db.XDBImpl.query(XDBImpl.java:147)
	at kd.bos.db.BaseDB.query(BaseDB.java:226)
	at kd.bos.db.DB.query(DB.java:97)
	at kd.bos.service.metadata.MetadataServiceReader.queryDB(MetadataServiceReader.java:824)
	at kd.bos.service.metadata.MetadataServiceReader.doQueryMetaData(MetadataServiceReader.java:637)
	at kd.bos.service.metadata.MetadataServiceReader.queryMeta(MetadataServiceReader.java:609)
	at kd.bos.service.metadata.MetadataServiceReader.queryFormMetaCache(MetadataServiceReader.java:603)
	at kd.bos.service.metadata.MetadataServiceReader.loadFormConfig(MetadataServiceReader.java:576)
	at kd.bos.service.metadata.MetadataServiceImpl.loadFormConfig(MetadataServiceImpl.java:254)
	at kd.bos.form.FormMetadataProvide.getFormConfig(FormMetadataProvide.java:54)
	at kd.bos.form.FormMetadataCache.getFormConfig(FormMetadataCache.java:62)
	at kd.bos.form.FormMetadataCache.getFormAppId(FormMetadataCache.java:41)
	at kd.bos.mservice.form.FormServiceImpl.getAppId(FormServiceImpl.java:147)
	at kd.bos.mservice.form.FormServiceImpl.getConfig(FormServiceImpl.java:178)
	at sun.reflect.GeneratedMethodAccessor692.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kd.bos.service.DispatchServiceImpl.invoke(DispatchServiceImpl.java:56)
	at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kd.bos.actiondispatcher.Invoker.invoke(Invoker.java:23)
	at kd.bos.actiondispatcher.ActionFilter.doFilter(ActionFilter.java:169)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.login.filter.LoginFilter.doFilter(LoginFilter.java:727)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.metric.instruments.servlet.MetricFilter.doFilter(MetricFilter.java:95)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.trace.instrument.web.TraceFilter.generateTraceId(TraceFilter.java:139)
	at kd.bos.trace.instrument.web.TraceFilter.doFilter(TraceFilter.java:103)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.framework.filter.ThreadLifeCycleFilter.doFilter(ThreadLifeCycleFilter.java:36)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.mservice.circuitbreaker.filter.web.CircuitbreakerFilter.lambda$doFilter$0(CircuitbreakerFilter.java:50)
	at kd.bos.mservice.circuitbreaker.noop.NoopCircuitbreaker.call(NoopCircuitbreaker.java:43)
	at kd.bos.mservice.circuitbreaker.filter.web.CircuitbreakerFilter.doFilter(CircuitbreakerFilter.java:49)
	at kd.bos.service.web.filter.KFilterConfig$2.doFilter(KFilterConfig.java:277)
	at kd.bos.service.web.filter.KDCommonFilter$2.doFilter(KDCommonFilter.java:69)
	at kd.bos.service.web.filter.KDCommonFilter.doFilter(KDCommonFilter.java:96)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Not supported feature or function
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1288)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at kd.bos.ksql.shell.KDPreparedStatement.executeQuery(KDPreparedStatement.java:348)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at kd.bos.util.jdbcproxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:36)
	at kd.bos.util.jdbcproxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:36)
	at kd.bos.trace.instrument.jdbc.PreparedStatementAOP.executeQuery(PreparedStatementAOP.java:51)
	at kd.bos.db.tx.DelegatePreparedStatement.executeQuery(DelegatePreparedStatement.java:40)
	at kd.bos.xdb.XDBExecutor.doQuery(XDBExecutor.java:218)
	at kd.bos.xdb.XDBExecutor.query(XDBExecutor.java:188)
	at kd.bos.xdb.ext.ExtXDB.query(ExtXDB.java:53)
	at kd.bos.db.XDBImpl.query(XDBImpl.java:130)
	... 89 more

### Actual Behavior

报错无法进入主页

### Expected Behavior

进入主页

### other information

表的定义
CREATE TABLE `t_meta_form` (
  `fnumber` varchar(36) NOT NULL DEFAULT ' ',
  `fkey` varchar(36) NOT NULL DEFAULT ' ',
  `ftype` smallint(6) NOT NULL DEFAULT '1',
  `fdata` longtext DEFAULT NULL,
  `ftimestamp` bigint(20) NOT NULL DEFAULT '0',
  `fid` varchar(36) NOT NULL DEFAULT ' ',
  PRIMARY KEY (`fnumber`, `fkey`, `ftype`),
  KEY `idx_meta_form_fid` (`fid`) BLOCK_SIZE 16384 GLOBAL
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = COMPACT COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0

**Comment by whhe** [comment]
prepare 默认是关闭的，打开试试

 ```
ALTER system set _ob_enable_prepared_statement =true;
```

**Comment by caifeizhi** [comment]
目前对于prepare statement + cursor fetch的场景，oceanbase在3.1.4以及之前的版本会报错：not support，可以通过关闭prepare statement或者关闭cursor fetch来规避；具体observer的代码如下：https://github.com/oceanbase/oceanbase/blob/da8879f6702804c4f1d83cc4c2d70542d64b0b34/src/observer/mysql/obmp_stmt_execute.cpp#L650

如果需要关闭prepare statement可以使用：
ALTER system set _ob_enable_prepared_statement =false;
如果需要关闭cursor fetch，可以使用修改jdbc链接串，关闭CursorFetch：
 String url = "jdbc:mysql://127.0.0.1:2883/test?**useCursorFetch=false**";
